FROM bcit/alpine:<%= image.labels['alpine_version'] %>
<%= snippet('labels', binding) -%>

ENV RUNUSER apache

COPY httpd-foreground /usr/local/bin/httpd-foreground
COPY httpd.conf /etc/apache2/httpd.conf
COPY 50-copy-config.sh /docker-entrypoint.d/50-copy-config.sh

RUN apk --no-cache add \
    libcap \
    apache2=<%= image.labels['httpd_version'] %>-r<%= image.labels['httpd_apk_release'] %> \
 && setcap CAP_NET_BIND_SERVICE=+eip /usr/sbin/httpd \
 && mkdir /etc/apache2/vhost.d /config /application \
 && chown 0:0 /etc/apache2/vhost.d /config /run/apache2 /var/log/apache2 /application \
 && chmod 775 /etc/apache2/vhost.d /config /run/apache2 /var/log/apache2 /application \
 && chmod 755 /usr/local/bin/httpd-foreground

EXPOSE 80
# https://httpd.apache.org/docs/2.4/stopping.html#gracefulstop
STOPSIGNAL WINCH

CMD ["/usr/local/bin/httpd-foreground"]
